package codegen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"text/template"
)

var (
	ignoredCommands = []string{
		"Login",
		"GetServerInformation",
	}
)

type generator struct {
	packageName      string
	operationsPrefix string
}

func NewGenerator(packageName, operationsPrefix string) *generator {
	return &generator{
		packageName:      packageName,
		operationsPrefix: operationsPrefix,
	}
}

func (g *generator) Read(def io.Reader) ([]Command, error) {
	var commands []Command
	err := json.NewDecoder(def).Decode(&commands)
	if err != nil {
		return nil, fmt.Errorf("error reading definitions file: %s", err.Error())
	}
	return commands, nil
}

func (g *generator) commonCommands(commands map[string][]Command) (common []Command) {
	gm := slices.Collect(maps.Keys(commands))[0]
	cmds := commands[gm]

	var otherCmds []Command
	for ogm, other := range commands {
		if gm == ogm {
			continue
		}
		otherCmds = append(otherCmds, other...)
	}

	for _, cmd := range cmds {
		if slices.ContainsFunc(otherCmds, func(c Command) bool {
			return cmd.Equals(c)
		}) {
			common = append(common, cmd)
		}
	}
	return
}

func (g *generator) cleanTarget() error {
	dir, err := os.ReadDir(fmt.Sprintf("./%s", g.packageName))
	if err != nil {
		return err
	}
	for _, e := range dir {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || !strings.HasPrefix(e.Name(), g.operationsPrefix) {
			continue
		}
		if err := os.Remove(filepath.Join(fmt.Sprintf("./%s", g.packageName), e.Name())); err != nil {
			return err
		}
	}
	return nil
}

func (g *generator) Generate(commands map[string][]Command) error {
	if err := g.cleanTarget(); err != nil {
		return err
	}

	common := g.commonCommands(commands)
	for _, command := range common {
		if slices.Contains(ignoredCommands, command.Id) {
			continue
		}
		if err := g.generateCommand(command, nil); err != nil {
			return err
		}
	}

	for gm, command := range commands {
		for _, cmd := range command {
			if slices.ContainsFunc(common, func(c Command) bool {
				return cmd.Equals(c)
			}) {
				continue
			}
			if err := g.generateCommand(cmd, &gm); err != nil {
				return err
			}
		}
	}

	return nil
}

const (
	operationsTemplate = `// Code generated by go-hll-rcon; DO NOT EDIT
{{- if .BuildTag }}

// +build {{.BuildTag}}

{{- end }}
package {{.PackageName}}

import (
	{{- range $index, $import := .Imports}}
	{{$import}}
	{{- end}}
)
{{if .Command.EnumValues }}
const (
	{{- range $name, $enumValue := .Command.EnumValues}}
	{{$name}} = {{if eq (printf "%T" $enumValue) "string"}}"{{$enumValue}}"{{else}}{{$enumValue}}{{end}}
	{{- end}}
)
{{ end }}
{{- range $index, $type := .Command.Types}}
{{$type.AsTypeDefinition}}
{{- if eq $type.AliasedType "string" }}
func (r {{$type.Name}}) String() string {
	return string(r)
}
{{- end }}
{{- end}}
// {{.Command.Name}} {{.Command.Description}}
func (c *Connection) {{.Command.Name}}({{.Command.Params.AsNamedArgsWithTypes}}){{.Command.Returns}}{
	{{if gt (len .Command.Returns) 1 }} return {{else}} _, err := {{end}}execCommand[{{.Command.RequestType.Name}}, {{if .Command.ReturnType }}{{.Command.ReturnType.Name}}{{else}}any{{end}}](ctx, c.socket, {{ if not .Command.InlineParameters}}{{.Command.RequestType.Name}}{
		{{- range $index, $param := .Command.Params}}
		{{- if ne $param.Name "ctx" }}{{$param.AsRequestAssignment}}{{end}}
		{{- end}}
	}{{else}}{{(index .Command.Params 1).Name}}{{end}})
	{{- if le (len .Command.Returns) 1 }}
	return err
	{{- end}}
}
{{if .Command.CommandName }}
func (r {{.Command.RequestType.Name}}) CommandName() string {
	return "{{.Command.CommandName}}"
}
{{end}}
`
)

type operationsTemplatePayload struct {
	PackageName string
	Imports     Imports
	Command     Command
	BuildTag    *string
}

func (g *generator) generateCommand(command Command, buildTag *string) error {
	prefix := ""
	if buildTag != nil {
		prefix = fmt.Sprintf("_%s", *buildTag)
	}
	filePath := fmt.Sprintf("./%s/%s%s%s.go", g.packageName, g.operationsPrefix, command.Id, prefix)
	f, err := os.OpenFile(filePath, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0755)
	if err != nil {
		return fmt.Errorf("error opening file: %s", err.Error())
	}
	defer f.Close()
	b := &bytes.Buffer{}
	tmpl := template.Must(template.New("operation").Parse(operationsTemplate))
	err = tmpl.Execute(b, operationsTemplatePayload{
		PackageName: g.packageName,
		Imports:     command.Imports(),
		Command:     command,
		BuildTag:    buildTag,
	})
	if err != nil {
		return fmt.Errorf("error executing template for operation %s: %s", command.Id, err.Error())
	}

	result, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("error formatting generated code for command %s: %s", command.Id, err.Error())
	}
	_, err = f.Write(result)
	return err
}
