package codegen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"os"
	"slices"
	"text/template"
)

var (
	ignoredCommands = []string{
		"Login",
		"GetServerInformation",
	}
)

type generator struct {
	packageName      string
	operationsPrefix string
}

func NewGenerator(packageName, operationsPrefix string) *generator {
	return &generator{
		packageName:      packageName,
		operationsPrefix: operationsPrefix,
	}
}

func (g *generator) Generate(defs io.Reader) error {
	var commands []Command
	err := json.NewDecoder(defs).Decode(&commands)
	if err != nil {
		return fmt.Errorf("error reading definitions file: %s", err.Error())
	}
	for _, command := range commands {
		if slices.Contains(ignoredCommands, command.Id) {
			continue
		}
		if err = g.generateCommand(command); err != nil {
			return err
		}
	}

	return nil
}

const (
	operationsTemplate = `// Code generated by go-hll-rcon; DO NOT EDIT
package {{.PackageName}}

import (
	{{- range $index, $import := .Imports}}
	{{$import}}
	{{- end}}
)
{{if .Command.EnumValues }}
const (
	{{- range $name, $enumValue := .Command.EnumValues}}
	{{$name}} = {{if eq (printf "%T" $enumValue) "string"}}"{{$enumValue}}"{{else}}{{$enumValue}}{{end}}
	{{- end}}
)
{{ end }}
{{- range $index, $type := .Command.Types}}
{{$type.AsTypeDefinition}}
{{- end}}
// {{.Command.Name}} {{.Command.Description}}
func (c *Connection) {{.Command.Name}}({{.Command.Params.AsNamedArgsWithTypes}}){{.Command.Returns}}{
	{{if gt (len .Command.Returns) 1 }} return {{else}} _, err := {{end}}execCommand[{{.Command.RequestType.Name}}, {{if .Command.ReturnType }}{{.Command.ReturnType.Name}}{{else}}any{{end}}](ctx, c.socket, {{ if not .Command.InlineParameters}}{{.Command.RequestType.Name}}{
		{{- range $index, $param := .Command.Params}}
		{{- if ne $param.Name "ctx" }}{{$param.AsRequestAssignment}}{{end}}
		{{- end}}
	}{{else}}{{(index .Command.Params 1).Name}}{{end}})
	{{if le (len .Command.Returns) 1 }}
	return err
	{{end}}
}
{{if .Command.CommandName }}
func (r {{.Command.RequestType.Name}}) CommandName() string {
	return "{{.Command.CommandName}}"
}
{{end}}
`
)

type operationsTemplatePayload struct {
	PackageName string
	Imports     Imports
	Command     Command
}

func (g *generator) generateCommand(command Command) error {
	f, err := os.OpenFile(fmt.Sprintf("./%s/%s%s.go", g.packageName, g.operationsPrefix, command.Id), os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0755)
	if err != nil {
		return fmt.Errorf("error opening file: %s", err.Error())
	}
	defer f.Close()
	b := &bytes.Buffer{}
	tmpl := template.Must(template.New("operation").Parse(operationsTemplate))
	err = tmpl.Execute(b, operationsTemplatePayload{
		PackageName: g.packageName,
		Imports:     command.Imports(),
		Command:     command,
	})
	if err != nil {
		return fmt.Errorf("error executing template for operation %s: %s", command.Id, err.Error())
	}

	result, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("error formatting generated code for command %s: %s", command.Id, err.Error())
	}
	_, err = f.Write(result)
	return err
}
