package codegen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"text/template"
)

var (
	ignoredCommands = []string{
		"Login",
		"GetServerInformation",
	}
)

type generator struct {
	packageName      string
	operationsPrefix string
}

func NewGenerator(packageName, operationsPrefix string) *generator {
	return &generator{
		packageName:      packageName,
		operationsPrefix: operationsPrefix,
	}
}

func (g *generator) Read(def io.Reader) ([]Command, error) {
	var commands []Command
	err := json.NewDecoder(def).Decode(&commands)
	if err != nil {
		return nil, fmt.Errorf("error reading definitions file: %s", err.Error())
	}
	return commands, nil
}

func (g *generator) commonCommands(commands map[string][]Command) (common []Command) {
	gm := slices.Collect(maps.Keys(commands))[0]
	cmds := commands[gm]

	var otherCmds []Command
	for ogm, other := range commands {
		if gm == ogm {
			continue
		}
		otherCmds = append(otherCmds, other...)
	}

	for _, cmd := range cmds {
		if slices.ContainsFunc(otherCmds, func(c Command) bool {
			return cmd.Equals(c)
		}) {
			common = append(common, cmd)
		}
	}
	return
}

func (g *generator) cleanTarget() error {
	dir, err := os.ReadDir(fmt.Sprintf("./%s", g.packageName))
	if err != nil {
		return err
	}
	for _, e := range dir {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || !strings.HasPrefix(e.Name(), g.operationsPrefix) {
			continue
		}
		if err := os.Remove(filepath.Join(fmt.Sprintf("./%s", g.packageName), e.Name())); err != nil {
			return err
		}
	}
	return nil
}

func (g *generator) Generate(commands map[string][]Command) error {
	if err := g.cleanTarget(); err != nil {
		return err
	}

	common := g.commonCommands(commands)
	for _, command := range common {
		if slices.Contains(ignoredCommands, command.Id) {
			continue
		}
		if err := g.generateCommand(command, nil); err != nil {
			return err
		}
	}

	var gameModes []string
	for gm, command := range commands {
		for _, cmd := range command {
			if slices.ContainsFunc(common, func(c Command) bool {
				return cmd.Equals(c)
			}) {
				continue
			}
			if err := g.generateCommand(cmd, &gm); err != nil {
				return err
			}
		}

		gameModes = append(gameModes, gm)
	}

	if err := g.generateGameConnection(gameModes); err != nil {
		return err
	}

	if err := g.generateGameModes(gameModes); err != nil {
		return err
	}

	return nil
}

const (
	operationsTemplate = `// Code generated by go-hll-rcon; DO NOT EDIT
package {{.PackageName}}

import (
	{{- range $index, $import := .Imports}}
	{{$import}}
	{{- end}}
)
{{if .Command.EnumValues }}
const (
	{{- range $name, $enumValue := .Command.EnumValues}}
	{{$name}} = {{if eq (printf "%T" $enumValue) "string"}}"{{$enumValue}}"{{else}}{{$enumValue}}{{end}}
	{{- end}}
)
{{ end }}
{{- range $index, $type := .Command.Types}}
{{$type.AsTypeDefinition}}
{{- if eq $type.AliasedType "string" }}
func (r {{$type.Name}}) String() string {
	return string(r)
}
{{- end }}
{{- end}}
// {{.Command.Name}} {{.Command.Description}}
func (c *{{.ClientName}}) {{.Command.Name}}({{.Command.Params.AsNamedArgsWithTypes}}){{.Command.Returns}}{
	{{if gt (len .Command.Returns) 1 }} return {{else}} _, err := {{end}}execCommand[{{.Command.RequestType.Name}}, {{if .Command.ReturnType }}{{.Command.ReturnType.Name}}{{else}}any{{end}}](ctx, c.socket, {{ if not .Command.InlineParameters}}{{.Command.RequestType.Name}}{
		{{- range $index, $param := .Command.Params}}
		{{- if ne $param.Name "ctx" }}{{$param.AsRequestAssignment}}{{end}}
		{{- end}}
	}{{else}}{{(index .Command.Params 1).Name}}{{end}})
	{{- if le (len .Command.Returns) 1 }}
	return err
	{{- end}}
}
{{if .Command.CommandName }}
func (r {{.Command.RequestType.Name}}) CommandName() string {
	return "{{.Command.CommandName}}"
}
{{end}}
`

	gameClientTemplate = `// Code generated by go-hll-rcon; DO NOT EDIT
package {{.PackageName}}

type {{.ClientName}} struct {
	Connection
}

func new{{.ClientName}}(id string, socket *socket) *{{.ClientName}} {
	return &{{.ClientName}}{
		Connection: Connection{
			id: id,
			socket: socket,
		},
	}
}
`

	gameConnectionTemplate = `// Code generated by go-hll-rcon; DO NOT EDIT
package {{.PackageName}}

type GameConnection interface {
	{{join .ClientNames " | "}} | *Connection
	getId() string
	getSocket() *socket
}
`
)

type gameConnectionTemplatePayload struct {
	PackageName string
	ClientNames []string
}

func gameModeToClientName(gameMode string) string {
	return strings.ToUpper(gameMode) + "Connection"
}

func toClientNames(gameModes []string) (res []string) {
	for _, mode := range gameModes {
		res = append(res, "*"+gameModeToClientName(mode))
	}
	return
}

func (g *generator) generateGameModes(gameModes []string) error {
	for _, mode := range gameModes {
		if err := g.generateGameMode(mode); err != nil {
			return err
		}
	}
	return nil
}

type gameClientTemplatePayload struct {
	PackageName string
	ClientName  string
}

func (g *generator) generateGameMode(gameMode string) error {
	filePath := fmt.Sprintf("./%s/%s_connection.go", g.packageName, gameMode)
	return writeTemplate(filePath, gameClientTemplate, gameClientTemplatePayload{
		PackageName: g.packageName,
		ClientName:  gameModeToClientName(gameMode),
	}, nil)
}

func (g *generator) generateGameConnection(gameModes []string) error {
	filePath := fmt.Sprintf("./%s/game_connection.go", g.packageName)
	return writeTemplate(filePath, gameConnectionTemplate, gameConnectionTemplatePayload{
		PackageName: g.packageName,
		ClientNames: toClientNames(gameModes),
	}, template.FuncMap{"join": strings.Join})
}

type operationsTemplatePayload struct {
	PackageName string
	Imports     Imports
	Command     Command
	ClientName  string
}

func (g *generator) generateCommand(command Command, gameMode *string) error {
	fileNameSuffix := ""
	typePrefix := ""
	clientName := "Connection"
	if gameMode != nil {
		fileNameSuffix = fmt.Sprintf("_%s", *gameMode)
		clientName = gameModeToClientName(*gameMode)
		typePrefix = strings.ToUpper(*gameMode)
	}
	filePath := fmt.Sprintf("./%s/%s%s%s.go", g.packageName, g.operationsPrefix, command.Id, fileNameSuffix)
	if err := writeTemplate(filePath, operationsTemplate, operationsTemplatePayload{
		PackageName: g.packageName,
		Imports:     command.Imports(),
		Command:     command.WithTypePrefix(typePrefix),
		ClientName:  clientName,
	}, nil); err != nil {
		return fmt.Errorf("error executing template for operation command %s: %w", command.Id, err)
	}
	return nil
}

func writeTemplate(filePath string, tpl string, data any, funcs template.FuncMap) error {
	f, err := os.OpenFile(filePath, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0755)
	if err != nil {
		return fmt.Errorf("error opening file: %s", err.Error())
	}
	defer f.Close()
	b := &bytes.Buffer{}
	tmpl := template.Must(template.New("").Funcs(funcs).Parse(tpl))
	err = tmpl.Execute(b, data)
	if err != nil {
		return err
	}

	result, err := format.Source(b.Bytes())
	if err != nil {
		return err
	}
	_, err = f.Write(result)
	return err
}
