// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

type HLLConnection struct {
	Connection
}

func newHLLConnection(id string, socket *socket) *HLLConnection {
	return &HLLConnection{
		Connection: Connection{
			id:     id,
			socket: socket,
		},
	}
}
