// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

type HLLVConnection struct {
	Connection
}

func newHLLVConnection(id string, socket *socket) *HLLVConnection {
	return &HLLVConnection{
		Connection: Connection{
			id:     id,
			socket: socket,
		},
	}
}
