// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type HLLVAddMapToSequence struct {
	MapName HLLVMapName `json:"MapName"`
	Index   int         `json:"Index"`
}

// AddMapToSequence Add map to server map sequence.
func (c *HLLVConnection) AddMapToSequence(ctx context.Context, MapName HLLVMapName, Index int) error {
	_, err := execCommand[HLLVAddMapToSequence, any](ctx, c.socket, HLLVAddMapToSequence{MapName: MapName, Index: Index})
	return err
}
