// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	AddAdminAdminGroupJunior    = "junior"
	AddAdminAdminGroupOwner     = "owner"
	AddAdminAdminGroupSenior    = "senior"
	AddAdminAdminGroupSpectator = "spectator"
)

type AddAdminAdminGroup string
type AddAdmin struct {
	PlayerId   string             `json:"PlayerId"`
	AdminGroup AddAdminAdminGroup `json:"AdminGroup"`
	Comment    string             `json:"Comment"`
}

// AddAdmin Add Admin: Add a player to the admin list.
func (c *Connection) AddAdmin(ctx context.Context, PlayerId string, AdminGroup AddAdminAdminGroup, Comment string) (any, error) {
	return execCommand[AddAdmin, any](ctx, c.socket, AddAdmin{PlayerId: PlayerId, AdminGroup: AdminGroup, Comment: Comment})

}
