// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type HLLAddMapToSequence struct {
	MapName HLLMapName `json:"MapName"`
	Index   int        `json:"Index"`
}

// AddMapToSequence Add map to server map sequence.
func (c *HLLConnection) AddMapToSequence(ctx context.Context, MapName HLLMapName, Index int) error {
	_, err := execCommand[HLLAddMapToSequence, any](ctx, c.socket, HLLAddMapToSequence{MapName: MapName, Index: Index})
	return err
}
