// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	HLLVMapNameCAMRANHPORTCONQUEST        = "wdeve_conquest_day"
	HLLVMapNameCAMRANHPORTDOMINATION      = "wdeve_domination_day"
	HLLVMapNameCAMRANHPORTNVAOFFENSIVE    = "wdeve_offensivenva_day"
	HLLVMapNameCAMRANHPORTUSOFFENSIVE     = "wdeve_offensiveus_day"
	HLLVMapNameCAMRANHPORTWARFARE         = "wdeve_warfare_day"
	HLLVMapNameHUẾOUTSKIRTSCONQUEST       = "wdevc_conquest_day"
	HLLVMapNameHUẾOUTSKIRTSDOMINATION     = "wdevc_domination_day"
	HLLVMapNameHUẾOUTSKIRTSNVAOFFENSIVE   = "wdevc_offensivenva_day"
	HLLVMapNameHUẾOUTSKIRTSUSOFFENSIVE    = "wdevc_offensiveus_day"
	HLLVMapNameHUẾOUTSKIRTSWARFARE        = "wdevc_warfare_day"
	HLLVMapNameQUẢNGNGÃICONQUEST          = "wdevb_conquest_day"
	HLLVMapNameQUẢNGNGÃIDOMINATION        = "wdevb_domination_day"
	HLLVMapNameQUẢNGNGÃINVAOFFENSIVE      = "wdevb_offensivenva_day"
	HLLVMapNameQUẢNGNGÃIUSOFFENSIVE       = "wdevb_offensiveus_day"
	HLLVMapNameQUẢNGNGÃIWARFARE           = "wdevb_warfare_day"
	HLLVMapNameTHANHHÒABRIDGECONQUEST     = "wdevf_conquest_day"
	HLLVMapNameTHANHHÒABRIDGEDOMINATION   = "wdevf_domination_day"
	HLLVMapNameTHANHHÒABRIDGENVAOFFENSIVE = "wdevf_offensivenva_day"
	HLLVMapNameTHANHHÒABRIDGEUSOFFENSIVE  = "wdevf_offensiveus_day"
	HLLVMapNameTHANHHÒABRIDGEWARFARE      = "wdevf_warfare_day"
	HLLVMapNameVẠNTƯỜNGCONQUEST           = "wdeva_conquest_day"
	HLLVMapNameVẠNTƯỜNGDOMINATION         = "wdeva_domination_day"
	HLLVMapNameVẠNTƯỜNGNVAOFFENSIVE       = "wdeva_offensivenva_day"
	HLLVMapNameVẠNTƯỜNGUSOFFENSIVE        = "wdeva_offensiveus_day"
	HLLVMapNameVẠNTƯỜNGWARFARE            = "wdeva_warfare_day"
	HLLVMapNameĐĂKTÔAIRFIELDCONQUEST      = "wdevd_conquest_day"
	HLLVMapNameĐĂKTÔAIRFIELDDOMINATION    = "wdevd_domination_day"
	HLLVMapNameĐĂKTÔAIRFIELDNVAOFFENSIVE  = "wdevd_offensivenva_day"
	HLLVMapNameĐĂKTÔAIRFIELDUSOFFENSIVE   = "wdevd_offensiveus_day"
	HLLVMapNameĐĂKTÔAIRFIELDWARFARE       = "wdevd_warfare_day"
)

type HLLVMapName string

func (r HLLVMapName) String() string {
	return string(r)
}

type HLLVAddMapToRotation struct {
	MapName HLLVMapName `json:"MapName"`
	Index   int         `json:"Index"`
}

// AddMapToRotation Add a new map to the map rotation at an index.
func (c *HLLVConnection) AddMapToRotation(ctx context.Context, MapName HLLVMapName, Index int) error {
	_, err := execCommand[HLLVAddMapToRotation, any](ctx, c.socket, HLLVAddMapToRotation{MapName: MapName, Index: Index})
	return err
}
