// Code generated by go-hll-rcon; DO NOT EDIT

//go:build hllv
// +build hllv

package rconv2

import (
	"context"
)

const (
	MapNameCAMRANHPORTCONQUEST        = "wdeve_conquest_day"
	MapNameCAMRANHPORTDOMINATION      = "wdeve_domination_day"
	MapNameCAMRANHPORTNVAOFFENSIVE    = "wdeve_offensivenva_day"
	MapNameCAMRANHPORTUSOFFENSIVE     = "wdeve_offensiveus_day"
	MapNameCAMRANHPORTWARFARE         = "wdeve_warfare_day"
	MapNameHUẾOUTSKIRTSCONQUEST       = "wdevc_conquest_day"
	MapNameHUẾOUTSKIRTSDOMINATION     = "wdevc_domination_day"
	MapNameHUẾOUTSKIRTSNVAOFFENSIVE   = "wdevc_offensivenva_day"
	MapNameHUẾOUTSKIRTSUSOFFENSIVE    = "wdevc_offensiveus_day"
	MapNameHUẾOUTSKIRTSWARFARE        = "wdevc_warfare_day"
	MapNameQUẢNGNGÃICONQUEST          = "wdevb_conquest_day"
	MapNameQUẢNGNGÃIDOMINATION        = "wdevb_domination_day"
	MapNameQUẢNGNGÃINVAOFFENSIVE      = "wdevb_offensivenva_day"
	MapNameQUẢNGNGÃIUSOFFENSIVE       = "wdevb_offensiveus_day"
	MapNameQUẢNGNGÃIWARFARE           = "wdevb_warfare_day"
	MapNameTHANHHÒABRIDGECONQUEST     = "wdevf_conquest_day"
	MapNameTHANHHÒABRIDGEDOMINATION   = "wdevf_domination_day"
	MapNameTHANHHÒABRIDGENVAOFFENSIVE = "wdevf_offensivenva_day"
	MapNameTHANHHÒABRIDGEUSOFFENSIVE  = "wdevf_offensiveus_day"
	MapNameTHANHHÒABRIDGEWARFARE      = "wdevf_warfare_day"
	MapNameVẠNTƯỜNGCONQUEST           = "wdeva_conquest_day"
	MapNameVẠNTƯỜNGDOMINATION         = "wdeva_domination_day"
	MapNameVẠNTƯỜNGNVAOFFENSIVE       = "wdeva_offensivenva_day"
	MapNameVẠNTƯỜNGUSOFFENSIVE        = "wdeva_offensiveus_day"
	MapNameVẠNTƯỜNGWARFARE            = "wdeva_warfare_day"
	MapNameĐĂKTÔAIRFIELDCONQUEST      = "wdevd_conquest_day"
	MapNameĐĂKTÔAIRFIELDDOMINATION    = "wdevd_domination_day"
	MapNameĐĂKTÔAIRFIELDNVAOFFENSIVE  = "wdevd_offensivenva_day"
	MapNameĐĂKTÔAIRFIELDUSOFFENSIVE   = "wdevd_offensiveus_day"
	MapNameĐĂKTÔAIRFIELDWARFARE       = "wdevd_warfare_day"
)

type MapName string

func (r MapName) String() string {
	return string(r)
}

type AddMapToRotation struct {
	MapName MapName `json:"MapName"`
	Index   int     `json:"Index"`
}

// AddMapToRotation Add a new map to the map rotation at an index.
func (c *Connection) AddMapToRotation(ctx context.Context, MapName MapName, Index int) error {
	_, err := execCommand[AddMapToRotation, any](ctx, c.socket, AddMapToRotation{MapName: MapName, Index: Index})
	return err
}
