// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type AddMapToSequence struct {
	MapName MapName `json:"MapName"`
	Index   int32   `json:"Index"`
}

// AddMapToSequence Add map to server map sequence.
func (c *Connection) AddMapToSequence(ctx context.Context, MapName MapName, Index int32) (any, error) {
	return execCommand[AddMapToSequence, any](ctx, c.socket, AddMapToSequence{MapName: MapName, Index: Index})

}
