// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type HLLChangeMap struct {
	MapName HLLMapName `json:"MapName"`
}

// ChangeMap Select a map to change the server map.
func (c *HLLConnection) ChangeMap(ctx context.Context, MapName HLLMapName) error {
	_, err := execCommand[HLLChangeMap, any](ctx, c.socket, HLLChangeMap{MapName: MapName})
	return err
}
