// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type HLLVChangeMap struct {
	MapName HLLVMapName `json:"MapName"`
}

// ChangeMap Select a map to change the server map.
func (c *HLLVConnection) ChangeMap(ctx context.Context, MapName HLLVMapName) error {
	_, err := execCommand[HLLVChangeMap, any](ctx, c.socket, HLLVChangeMap{MapName: MapName})
	return err
}
