// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	HLLDisbandPlatoonTeamIndexAllies = 2
	HLLDisbandPlatoonTeamIndexAxis   = 1
)

type HLLDisbandPlatoonTeamIndex int
type HLLDisbandPlatoon struct {
	TeamIndex  HLLDisbandPlatoonTeamIndex `json:"TeamIndex"`
	SquadIndex int                        `json:"SquadIndex"`
	Reason     string                     `json:"Reason"`
}

// DisbandPlatoon Disband a squad and force players within the platoon to redeploy.
func (c *HLLConnection) DisbandPlatoon(ctx context.Context, TeamIndex HLLDisbandPlatoonTeamIndex, SquadIndex int, Reason string) error {
	_, err := execCommand[HLLDisbandPlatoon, any](ctx, c.socket, HLLDisbandPlatoon{TeamIndex: TeamIndex, SquadIndex: SquadIndex, Reason: Reason})
	return err
}
