// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	DisbandPlatoonTeamIndexAllies = 2
	DisbandPlatoonTeamIndexAxis   = 1
)

type DisbandPlatoonTeamIndex string
type DisbandPlatoon struct {
	TeamIndex  DisbandPlatoonTeamIndex `json:"TeamIndex"`
	SquadIndex int32                   `json:"SquadIndex"`
	Reason     string                  `json:"Reason"`
}

// DisbandPlatoon Disband a squad and force players within the platoon to redeploy.
func (c *Connection) DisbandPlatoon(ctx context.Context, TeamIndex DisbandPlatoonTeamIndex, SquadIndex int32, Reason string) (any, error) {
	return execCommand[DisbandPlatoon, any](ctx, c.socket, DisbandPlatoon{TeamIndex: TeamIndex, SquadIndex: SquadIndex, Reason: Reason})

}
