// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	HLLVDisbandPlatoonTeamIndexNVA = 1
	HLLVDisbandPlatoonTeamIndexUS  = 2
)

type HLLVDisbandPlatoonTeamIndex int
type HLLVDisbandPlatoon struct {
	TeamIndex  HLLVDisbandPlatoonTeamIndex `json:"TeamIndex"`
	SquadIndex int                         `json:"SquadIndex"`
	Reason     string                      `json:"Reason"`
}

// DisbandPlatoon Disband a squad and force players within the platoon to redeploy.
func (c *HLLVConnection) DisbandPlatoon(ctx context.Context, TeamIndex HLLVDisbandPlatoonTeamIndex, SquadIndex int, Reason string) error {
	_, err := execCommand[HLLVDisbandPlatoon, any](ctx, c.socket, HLLVDisbandPlatoon{TeamIndex: TeamIndex, SquadIndex: SquadIndex, Reason: Reason})
	return err
}
