// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	ForceTeamSwitchForceModeImmediate = 1
	ForceTeamSwitchForceModeOnDeath   = 0
)

type ForceTeamSwitchForceMode string
type ForceTeamSwitch struct {
	PlayerId  string                   `json:"PlayerId"`
	ForceMode ForceTeamSwitchForceMode `json:"ForceMode"`
}

// ForceTeamSwitch Force Team Switch: Forces a player to switch teams.
func (c *Connection) ForceTeamSwitch(ctx context.Context, PlayerId string, ForceMode ForceTeamSwitchForceMode) (any, error) {
	return execCommand[ForceTeamSwitch, any](ctx, c.socket, ForceTeamSwitch{PlayerId: PlayerId, ForceMode: ForceMode})

}
