// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	GetSessionInfoGameModeConquest  = "Conquest"
	GetSessionInfoGameModeOffensive = "Offensive"
	GetSessionInfoGameModeSkirmish  = "Skirmish"
	GetSessionInfoGameModeWarfare   = "Warfare"
	GetSessionInfoNameSession       = "session"
)

type GetSessionInfoName string

func (r GetSessionInfoName) String() string {
	return string(r)
}

type GetSessionInfo struct {
	Name string `json:"Name"`
}
type GetSessionInfoResponse struct {
	ServerName       string                 `json:"serverName"`
	MapName          string                 `json:"mapName"`
	GameMode         GetSessionInfoGameMode `json:"gameMode"`
	MaxPlayerCount   int32                  `json:"maxPlayerCount"`
	PlayerCount      int32                  `json:"playerCount"`
	MaxQueueCount    int32                  `json:"maxQueueCount"`
	QueueCount       int32                  `json:"queueCount"`
	MaxVIPQueueCount int32                  `json:"maxVIPQueueCount"`
	VIPQueueCount    int32                  `json:"vIPQueueCount"`
}
type GetSessionInfoGameMode string

func (r GetSessionInfoGameMode) String() string {
	return string(r)
}

// GetSessionInfo Get information about current game state of the server
func (c *Connection) GetSessionInfo(ctx context.Context) (*GetSessionInfoResponse, error) {
	return execCommand[GetSessionInfo, GetSessionInfoResponse](ctx, c.socket, GetSessionInfo{Name: "session"})

}

func (r GetSessionInfo) CommandName() string {
	return "GetServerInformation"
}
