// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type GetVoteKickEnabled struct {
}

// GetVoteKickEnabled Get Vote Kick Enabled: None
func (c *Connection) GetVoteKickEnabled(ctx context.Context) (any, error) {
	return execCommand[GetVoteKickEnabled, any](ctx, c.socket, GetVoteKickEnabled{})

}
