// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	GetServerInformationNameMaprotation  = "maprotation"
	GetServerInformationNameMapsequence  = "mapsequence"
	GetServerInformationNamePlayer       = "player"
	GetServerInformationNamePlayers      = "players"
	GetServerInformationNameServerconfig = "serverconfig"
	GetServerInformationNameSession      = "session"
)

type GetServerInformationName string
type GetServerInformation struct {
	Name  GetServerInformationName `json:"Name"`
	Value string                   `json:"Value"`
}

// GetServerInformation None
func (c *Connection) GetServerInformation(ctx context.Context, Name GetServerInformationName, Value string) (any, error) {
	return execCommand[GetServerInformation, any](ctx, c.socket, GetServerInformation{Name: Name, Value: Value})

}
