// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	GetMapSequenceNameMapsequence = "mapsequence"
)

type GetMapSequenceName string
type GetMapSequence struct {
	Name string `json:"Name"`
}

// GetMapSequence Get Map Sequence: Get current map sequence
func (c *Connection) GetMapSequence(ctx context.Context) (any, error) {
	return execCommand[GetMapSequence, any](ctx, c.socket, GetMapSequence{Name: "mapsequence"})

}

func (r GetMapSequence) CommandName() string {
	return "GetServerInformation"
}
