// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type GetAdminGroups struct {
}
type GetAdminGroupsResponse struct {
	GroupNames []GetAdminGroupsGroupName `json:"GroupNames"`
}
type GetAdminGroupsGroupName string

// GetAdminGroups Get Admin Groups: Get a list of admin user groups.
func (c *Connection) GetAdminGroups(ctx context.Context) (*GetAdminGroupsResponse, error) {
	return execCommand[GetAdminGroups, GetAdminGroupsResponse](ctx, c.socket, GetAdminGroups{})

}
