// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	GetPlayerNamePlayer                 = "player"
	GetPlayerPlatformEpicGameStore      = "epic"
	GetPlayerPlatformPlayStation5       = "ps5"
	GetPlayerPlatformPlayStationNetwork = "psn"
	GetPlayerPlatformSteam              = "steam"
	GetPlayerPlatformXboxGamePass       = "xbl"
	GetPlayerPlatformXboxSeriesX        = "xsx"
	GetPlayerRoleAntiTank               = 7
	GetPlayerRoleArmyCommander          = 13
	GetPlayerRoleAssault                = 1
	GetPlayerRoleAutomaticRifleman      = 2
	GetPlayerRoleCrewman                = 11
	GetPlayerRoleEngineer               = 8
	GetPlayerRoleHeavyMachineGunner     = 6
	GetPlayerRoleMedic                  = 3
	GetPlayerRoleOfficer                = 9
	GetPlayerRoleRifleman               = 0
	GetPlayerRoleSniper                 = 10
	GetPlayerRoleSpotter                = 4
	GetPlayerRoleSupport                = 5
	GetPlayerRoleTankCommander          = 12
	GetPlayerTeamB8A                    = 5
	GetPlayerTeamCW                     = 3
	GetPlayerTeamDAK                    = 4
	GetPlayerTeamGER                    = 0
	GetPlayerTeamME                     = 1
	GetPlayerTeamSOV                    = 2
	GetPlayerTeamUNASSIGNED             = 6
)

type GetPlayerName string
type GetPlayer struct {
	Name  string `json:"Name"`
	Value string `json:"Value"`
}
type GetPlayerResponse struct {
	Id                   string              `json:"iD"`
	Platform             GetPlayerPlatform   `json:"platform"`
	Name                 string              `json:"name"`
	ClanTag              string              `json:"clanTag"`
	EpicOnlineServicesId string              `json:"eOSID"`
	Level                int32               `json:"level"`
	Team                 GetPlayerTeam       `json:"team"`
	Role                 GetPlayerRole       `json:"role"`
	Platoon              string              `json:"platoon"`
	Loadout              string              `json:"loadout"`
	Kills                int32               `json:"kills"`
	Deaths               int32               `json:"deaths"`
	ScoreData            GetPlayerScoreDatum `json:"scoreData"`
	Position             GetPlayerPosition   `json:"worldPosition"`
}
type GetPlayerPlatform string
type GetPlayerTeam int32
type GetPlayerRole int32
type GetPlayerScoreDatum struct {
	Combat    int32 `json:"cOMBAT"`
	Offensive int32 `json:"offense"`
	Defensive int32 `json:"defense"`
	Support   int32 `json:"support"`
}
type GetPlayerPosition struct {
	X int32 `json:"x"`
	Y int32 `json:"y"`
	Z int32 `json:"z"`
}

// GetPlayer Get player information of a connected player
func (c *Connection) GetPlayer(ctx context.Context, Value string) (*GetPlayerResponse, error) {
	return execCommand[GetPlayer, GetPlayerResponse](ctx, c.socket, GetPlayer{Name: "player", Value: Value})

}

func (r GetPlayer) CommandName() string {
	return "GetServerInformation"
}
