// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type HLLVGetSectorLayout struct {
}

// GetSectorLayout Retrieves custom sectors layouts for maps.
func (c *HLLVConnection) GetSectorLayout(ctx context.Context) error {
	_, err := execCommand[HLLVGetSectorLayout, any](ctx, c.socket, HLLVGetSectorLayout{})
	return err
}
