// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type GetVoteKickThreshold struct {
}
type GetVoteKickThresholdResponse struct {
	VoteThresholdList []GetVoteKickThresholdVoteThresholdList `json:"voteThresholdList"`
}
type GetVoteKickThresholdVoteThresholdList struct {
	PlayerCount   int32 `json:"playerCount"`
	VoteThreshold int32 `json:"voteThreshold"`
}

// GetVoteKickThreshold None
func (c *Connection) GetVoteKickThreshold(ctx context.Context) (*GetVoteKickThresholdResponse, error) {
	return execCommand[GetVoteKickThreshold, GetVoteKickThresholdResponse](ctx, c.socket, GetVoteKickThreshold{})

}
