// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	GetServerConfigNameServerconfig         = "serverconfig"
	GetServerConfigSupportedPlatformsEo     = "eos"
	GetServerConfigSupportedPlatformsSteam  = "Steam"
	GetServerConfigSupportedPlatformsWinGDK = "WinGDK"
)

type GetServerConfigName string
type GetServerConfig struct {
	Name string `json:"Name"`
}
type GetServerConfigResponse struct {
	ServerName         string                             `json:"serverName"`
	BuildNumber        string                             `json:"buildNumber"`
	BuildRevision      string                             `json:"buildRevision"`
	SupportedPlatforms []GetServerConfigSupportedPlatform `json:"supportedPlatforms"`
}
type GetServerConfigSupportedPlatform string

// GetServerConfig Get Server Config: Get metadata of server
func (c *Connection) GetServerConfig(ctx context.Context) (*GetServerConfigResponse, error) {
	return execCommand[GetServerConfig, GetServerConfigResponse](ctx, c.socket, GetServerConfig{Name: "serverconfig"})

}

func (r GetServerConfig) CommandName() string {
	return "GetServerInformation"
}
