// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type GetVoteKickThreshold struct {
}

// GetVoteKickThreshold None
func (c *Connection) GetVoteKickThreshold(ctx context.Context) (any, error) {
	return execCommand[GetVoteKickThreshold, any](ctx, c.socket, GetVoteKickThreshold{})

}
