// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	GetMapRotationNameMaprotation = "maprotation"
)

type GetMapRotationName string
type GetMapRotation struct {
	Name string `json:"Name"`
}

// GetMapRotation Get current map rotation
func (c *Connection) GetMapRotation(ctx context.Context) (any, error) {
	return execCommand[GetMapRotation, any](ctx, c.socket, GetMapRotation{Name: "maprotation"})

}

func (r GetMapRotation) CommandName() string {
	return "GetServerInformation"
}
