// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type GetKickIdleDuration struct {
}

// GetKickIdleDuration Get Kick Idle Duration: None
func (c *Connection) GetKickIdleDuration(ctx context.Context) (any, error) {
	return execCommand[GetKickIdleDuration, any](ctx, c.socket, GetKickIdleDuration{})

}
