// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type GetAutoBalanceThreshold struct {
}

// GetAutoBalanceThreshold None
func (c *Connection) GetAutoBalanceThreshold(ctx context.Context) (any, error) {
	return execCommand[GetAutoBalanceThreshold, any](ctx, c.socket, GetAutoBalanceThreshold{})

}
