// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
	"time"
)

type GetTemporaryBans struct {
}
type GetTemporaryBansResponse struct {
	BanList []GetTemporaryBansBanList `json:"banList"`
}
type GetTemporaryBansBanList struct {
	Id        string    `json:"userId"`
	Name      string    `json:"userName"`
	Banned    time.Time `json:"timeOfBanning"`
	Duration  int32     `json:"durationHours"`
	Reason    string    `json:"banReason"`
	AdminName string    `json:"adminName"`
}

// GetTemporaryBans Get Temporary Bans: Retrieve a list of players who have temporary bans.
func (c *Connection) GetTemporaryBans(ctx context.Context) (*GetTemporaryBansResponse, error) {
	return execCommand[GetTemporaryBans, GetTemporaryBansResponse](ctx, c.socket, GetTemporaryBans{})

}
