// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type GetServerChangelist struct {
}

// GetServerChangelist Retrieves the servers changelist number.
func (c *Connection) GetServerChangelist(ctx context.Context) (any, error) {
	return execCommand[GetServerChangelist, any](ctx, c.socket, GetServerChangelist{})

}
