// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type GetTeamSwitchCooldown struct {
}

// GetTeamSwitchCooldown Get Team Switch Cooldown: None
func (c *Connection) GetTeamSwitchCooldown(ctx context.Context) (any, error) {
	return execCommand[GetTeamSwitchCooldown, any](ctx, c.socket, GetTeamSwitchCooldown{})

}
