// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	GetPlayersNamePlayers                = "players"
	GetPlayersPlatformEpicGameStore      = "epic"
	GetPlayersPlatformPlayStation5       = "ps5"
	GetPlayersPlatformPlayStationNetwork = "psn"
	GetPlayersPlatformSteam              = "steam"
	GetPlayersPlatformXboxGamePass       = "xbl"
	GetPlayersPlatformXboxSeriesX        = "xsx"
	GetPlayersRoleAntiTank               = 7
	GetPlayersRoleArmyCommander          = 13
	GetPlayersRoleAssault                = 1
	GetPlayersRoleAutomaticRifleman      = 2
	GetPlayersRoleCrewman                = 11
	GetPlayersRoleEngineer               = 8
	GetPlayersRoleHeavyMachineGunner     = 6
	GetPlayersRoleMedic                  = 3
	GetPlayersRoleOfficer                = 9
	GetPlayersRoleRifleman               = 0
	GetPlayersRoleSniper                 = 10
	GetPlayersRoleSpotter                = 4
	GetPlayersRoleSupport                = 5
	GetPlayersRoleTankCommander          = 12
	GetPlayersTeamB8A                    = 5
	GetPlayersTeamCW                     = 3
	GetPlayersTeamDAK                    = 4
	GetPlayersTeamGER                    = 0
	GetPlayersTeamME                     = 1
	GetPlayersTeamSOV                    = 2
	GetPlayersTeamUNASSIGNED             = 6
)

type GetPlayersName string
type GetPlayers struct {
	Name string `json:"Name"`
}
type GetPlayersResponse struct {
	Players []GetPlayersPlayer `json:"players"`
}
type GetPlayersPlatform string
type GetPlayersTeam string
type GetPlayersRole string
type GetPlayersScoreDatum struct {
	Combat    int32 `json:"cOMBAT"`
	Offensive int32 `json:"offense"`
	Defensive int32 `json:"defense"`
	Support   int32 `json:"support"`
}
type GetPlayersPosition struct {
	X int32 `json:"x"`
	Y int32 `json:"y"`
	Z int32 `json:"z"`
}
type GetPlayersPlayer struct {
	Id                   string               `json:"iD"`
	Platform             GetPlayersPlatform   `json:"platform"`
	Name                 string               `json:"name"`
	ClanTag              string               `json:"clanTag"`
	EpicOnlineServicesId string               `json:"eOSID"`
	Level                int32                `json:"level"`
	Team                 GetPlayersTeam       `json:"team"`
	Role                 GetPlayersRole       `json:"role"`
	Platoon              string               `json:"platoon"`
	Loadout              string               `json:"loadout"`
	Kills                int32                `json:"kills"`
	Deaths               int32                `json:"deaths"`
	ScoreData            GetPlayersScoreDatum `json:"scoreData"`
	Position             GetPlayersPosition   `json:"worldPosition"`
}

// GetPlayers Get a list of players from the server
func (c *Connection) GetPlayers(ctx context.Context) (*GetPlayersResponse, error) {
	return execCommand[GetPlayers, GetPlayersResponse](ctx, c.socket, GetPlayers{Name: "players"})

}

func (r GetPlayers) CommandName() string {
	return "GetServerInformation"
}
