// Code generated by go-hll-rcon; DO NOT EDIT

//go:build hllv
// +build hllv

package rconv2

import (
	"context"
)

type GetSectorLayout struct {
}

// GetSectorLayout Retrieves custom sectors layouts for maps.
func (c *Connection) GetSectorLayout(ctx context.Context) error {
	_, err := execCommand[GetSectorLayout, any](ctx, c.socket, GetSectorLayout{})
	return err
}
