// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type GetHighPingThreshold struct {
}

// GetHighPingThreshold Get High Ping Threshold: None
func (c *Connection) GetHighPingThreshold(ctx context.Context) (any, error) {
	return execCommand[GetHighPingThreshold, any](ctx, c.socket, GetHighPingThreshold{})

}
