// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type GetAdminLog struct {
}
type GetAdminLogResponse struct {
	Entries []GetAdminLogEntry `json:"entries"`
}
type GetAdminLogEntry struct {
	Timestamp string `json:"timestamp"`
	Message   string `json:"message"`
}

// GetAdminLog Get Admin Log: Retrieve admin log.
func (c *Connection) GetAdminLog(ctx context.Context) (*GetAdminLogResponse, error) {
	return execCommand[GetAdminLog, GetAdminLogResponse](ctx, c.socket, GetAdminLog{})

}
