// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type GetAutoBalanceEnabled struct {
}

// GetAutoBalanceEnabled Get Auto Balance Enabled: None
func (c *Connection) GetAutoBalanceEnabled(ctx context.Context) (any, error) {
	return execCommand[GetAutoBalanceEnabled, any](ctx, c.socket, GetAutoBalanceEnabled{})

}
