// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type KickPlayer struct {
	Reason   string `json:"Reason"`
	PlayerId string `json:"PlayerId"`
}

// KickPlayer Kick Player: Select player to kick and add a reason.
func (c *Connection) KickPlayer(ctx context.Context, Reason string, PlayerId string) (any, error) {
	return execCommand[KickPlayer, any](ctx, c.socket, KickPlayer{Reason: Reason, PlayerId: PlayerId})

}
