// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type Login struct {
}

// Login None
func (c *Connection) Login(ctx context.Context) error {
	_, err := execCommand[Login, any](ctx, c.socket, Login{})

	return err

}
