// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type Login struct {
}

// Login Connect: None
func (c *Connection) Login(ctx context.Context) (any, error) {
	return execCommand[Login, any](ctx, c.socket, Login{})

}
