// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type MoveMapInSequence struct {
	CurrentIndex int32 `json:"CurrentIndex"`
	NewIndex     int32 `json:"NewIndex"`
}

// MoveMapInSequence Change the position on a map in the server queue
func (c *Connection) MoveMapInSequence(ctx context.Context, CurrentIndex int32, NewIndex int32) error {
	_, err := execCommand[MoveMapInSequence, any](ctx, c.socket, MoveMapInSequence{CurrentIndex: CurrentIndex, NewIndex: NewIndex})

	return err

}
