// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type MessagePlayer struct {
	Message  string `json:"Message"`
	PlayerId string `json:"PlayerId"`
}

// MessagePlayer Message Player: Create a message to send to a player in game.
func (c *Connection) MessagePlayer(ctx context.Context, Message string, PlayerId string) (any, error) {
	return execCommand[MessagePlayer, any](ctx, c.socket, MessagePlayer{Message: Message, PlayerId: PlayerId})

}
