// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type RemovePlayerFromPlatoon struct {
	PlayerId string `json:"PlayerId"`
	Reason   string `json:"Reason"`
}

// RemovePlayerFromPlatoon Removes a player from their current platoon.
func (c *Connection) RemovePlayerFromPlatoon(ctx context.Context, PlayerId string, Reason string) (any, error) {
	return execCommand[RemovePlayerFromPlatoon, any](ctx, c.socket, RemovePlayerFromPlatoon{PlayerId: PlayerId, Reason: Reason})

}
