// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type RemoveBannedWords struct {
	BannedWords string `json:"BannedWords"`
}

// RemoveBannedWords Remove banned words from the profanity filter. Separate words with commas.
func (c *Connection) RemoveBannedWords(ctx context.Context, BannedWords string) (any, error) {
	return execCommand[RemoveBannedWords, any](ctx, c.socket, RemoveBannedWords{BannedWords: BannedWords})

}
