// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	HLLVRemoveMatchTimerGameModeConquest   = "Conquest"
	HLLVRemoveMatchTimerGameModeDomination = "Domination"
	HLLVRemoveMatchTimerGameModeOffensive  = "Offensive"
	HLLVRemoveMatchTimerGameModeWarfare    = "Warfare"
)

type HLLVRemoveMatchTimerGameMode string

func (r HLLVRemoveMatchTimerGameMode) String() string {
	return string(r)
}

type HLLVRemoveMatchTimer struct {
	GameMode HLLVRemoveMatchTimerGameMode `json:"GameMode"`
}

// RemoveMatchTimer Remove the match timer override for a specific game-mode.
func (c *HLLVConnection) RemoveMatchTimer(ctx context.Context, GameMode HLLVRemoveMatchTimerGameMode) error {
	_, err := execCommand[HLLVRemoveMatchTimer, any](ctx, c.socket, HLLVRemoveMatchTimer{GameMode: GameMode})
	return err
}
