// Code generated by go-hll-rcon; DO NOT EDIT

//go:build hll
// +build hll

package rconv2

import (
	"context"
)

const (
	RemoveWarmupTimerGameModeConquest = "Conquest"
	RemoveWarmupTimerGameModeSkirmish = "Skirmish"
	RemoveWarmupTimerGameModeWarfare  = "Warfare"
)

type RemoveWarmupTimerGameMode string

func (r RemoveWarmupTimerGameMode) String() string {
	return string(r)
}

type RemoveWarmupTimer struct {
	GameMode RemoveWarmupTimerGameMode `json:"GameMode"`
}

// RemoveWarmupTimer Remove warmup timer override for a specific game mode.
func (c *Connection) RemoveWarmupTimer(ctx context.Context, GameMode RemoveWarmupTimerGameMode) error {
	_, err := execCommand[RemoveWarmupTimer, any](ctx, c.socket, RemoveWarmupTimer{GameMode: GameMode})
	return err
}
