// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	RemoveWarmupTimerGameModeSkirmish = "Skirmish"
	RemoveWarmupTimerGameModeWarfare  = "Warfare"
)

type RemoveWarmupTimerGameMode string
type RemoveWarmupTimer struct {
	GameMode RemoveWarmupTimerGameMode `json:"GameMode"`
}

// RemoveWarmupTimer Remove Warmup Timer: Remove warmup timer override for a specific game mode.
func (c *Connection) RemoveWarmupTimer(ctx context.Context, GameMode RemoveWarmupTimerGameMode) (any, error) {
	return execCommand[RemoveWarmupTimer, any](ctx, c.socket, RemoveWarmupTimer{GameMode: GameMode})

}
