// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	HLLVRemoveWarmupTimerGameModeConquest   = "Conquest"
	HLLVRemoveWarmupTimerGameModeDomination = "Domination"
	HLLVRemoveWarmupTimerGameModeWarfare    = "Warfare"
)

type HLLVRemoveWarmupTimerGameMode string

func (r HLLVRemoveWarmupTimerGameMode) String() string {
	return string(r)
}

type HLLVRemoveWarmupTimer struct {
	GameMode HLLVRemoveWarmupTimerGameMode `json:"GameMode"`
}

// RemoveWarmupTimer Remove warmup timer override for a specific game mode.
func (c *HLLVConnection) RemoveWarmupTimer(ctx context.Context, GameMode HLLVRemoveWarmupTimerGameMode) error {
	_, err := execCommand[HLLVRemoveWarmupTimer, any](ctx, c.socket, HLLVRemoveWarmupTimer{GameMode: GameMode})
	return err
}
