// Code generated by go-hll-rcon; DO NOT EDIT

//go:build hllv
// +build hllv

package rconv2

import (
	"context"
)

type RemoveSectorLayout struct {
	MapId MapName `json:"MapId"`
}

// RemoveSectorLayout Remove a custom sector layout from the server config.
func (c *Connection) RemoveSectorLayout(ctx context.Context, MapId MapName) error {
	_, err := execCommand[RemoveSectorLayout, any](ctx, c.socket, RemoveSectorLayout{MapId: MapId})
	return err
}
