// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type HLLVRemoveSectorLayout struct {
	MapId HLLVMapName `json:"MapId"`
}

// RemoveSectorLayout Remove a custom sector layout from the server config.
func (c *HLLVConnection) RemoveSectorLayout(ctx context.Context, MapId HLLVMapName) error {
	_, err := execCommand[HLLVRemoveSectorLayout, any](ctx, c.socket, HLLVRemoveSectorLayout{MapId: MapId})
	return err
}
