// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type RemoveMapFromRotation struct {
	Index int32 `json:"Index"`
}

// RemoveMapFromRotation Remove map from the map rotation at an index.
func (c *Connection) RemoveMapFromRotation(ctx context.Context, Index int32) (any, error) {
	return execCommand[RemoveMapFromRotation, any](ctx, c.socket, RemoveMapFromRotation{Index: Index})

}
