// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	HLLRemoveWarmupTimerGameModeConquest = "Conquest"
	HLLRemoveWarmupTimerGameModeSkirmish = "Skirmish"
	HLLRemoveWarmupTimerGameModeWarfare  = "Warfare"
)

type HLLRemoveWarmupTimerGameMode string

func (r HLLRemoveWarmupTimerGameMode) String() string {
	return string(r)
}

type HLLRemoveWarmupTimer struct {
	GameMode HLLRemoveWarmupTimerGameMode `json:"GameMode"`
}

// RemoveWarmupTimer Remove warmup timer override for a specific game mode.
func (c *HLLConnection) RemoveWarmupTimer(ctx context.Context, GameMode HLLRemoveWarmupTimerGameMode) error {
	_, err := execCommand[HLLRemoveWarmupTimer, any](ctx, c.socket, HLLRemoveWarmupTimer{GameMode: GameMode})
	return err
}
