// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type RemoveAdmin struct {
	PlayerId string `json:"PlayerId"`
}

// RemoveAdmin Remove player from admin privileges.
func (c *Connection) RemoveAdmin(ctx context.Context, PlayerId string) (any, error) {
	return execCommand[RemoveAdmin, any](ctx, c.socket, RemoveAdmin{PlayerId: PlayerId})

}
