// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	HLLRemoveMatchTimerGameModeConquest  = "Conquest"
	HLLRemoveMatchTimerGameModeOffensive = "Offensive"
	HLLRemoveMatchTimerGameModeSkirmish  = "Skirmish"
	HLLRemoveMatchTimerGameModeWarfare   = "Warfare"
)

type HLLRemoveMatchTimerGameMode string

func (r HLLRemoveMatchTimerGameMode) String() string {
	return string(r)
}

type HLLRemoveMatchTimer struct {
	GameMode HLLRemoveMatchTimerGameMode `json:"GameMode"`
}

// RemoveMatchTimer Remove the match timer override for a specific game-mode.
func (c *HLLConnection) RemoveMatchTimer(ctx context.Context, GameMode HLLRemoveMatchTimerGameMode) error {
	_, err := execCommand[HLLRemoveMatchTimer, any](ctx, c.socket, HLLRemoveMatchTimer{GameMode: GameMode})
	return err
}
