// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type HLLVSetNoticeMessage struct {
	Message string `json:"Message"`
}

// SetNoticeMessage Send a message to the server.
func (c *HLLVConnection) SetNoticeMessage(ctx context.Context, Message string) error {
	_, err := execCommand[HLLVSetNoticeMessage, any](ctx, c.socket, HLLVSetNoticeMessage{Message: Message})
	return err
}
