// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	SetMapShuffleEnabledEnableOff = false
	SetMapShuffleEnabledEnableOn  = true
)

type SetMapShuffleEnabledEnable string
type SetMapShuffleEnabled struct {
	Enable SetMapShuffleEnabledEnable `json:"Enable"`
}

// SetMapShuffleEnabled Set Map Shuffle Enabled: Randomises the server map queue
func (c *Connection) SetMapShuffleEnabled(ctx context.Context, Enable SetMapShuffleEnabledEnable) (any, error) {
	return execCommand[SetMapShuffleEnabled, any](ctx, c.socket, SetMapShuffleEnabled{Enable: Enable})

}
