// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	SetAutoBalanceEnabledEnableOff = false
	SetAutoBalanceEnabledEnableOn  = true
)

type SetAutoBalanceEnabledEnable string
type SetAutoBalanceEnabled struct {
	Enable SetAutoBalanceEnabledEnable `json:"Enable"`
}

// SetAutoBalanceEnabled Set Auto Balance Enabled: Enable or disable the auto balance.
func (c *Connection) SetAutoBalanceEnabled(ctx context.Context, Enable SetAutoBalanceEnabledEnable) (any, error) {
	return execCommand[SetAutoBalanceEnabled, any](ctx, c.socket, SetAutoBalanceEnabled{Enable: Enable})

}
