// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	HLLVSetMatchTimerGameModeConquest   = "Conquest"
	HLLVSetMatchTimerGameModeDomination = "Domination"
	HLLVSetMatchTimerGameModeOffensive  = "Offensive"
	HLLVSetMatchTimerGameModeWarfare    = "Warfare"
)

type HLLVSetMatchTimerGameMode string

func (r HLLVSetMatchTimerGameMode) String() string {
	return string(r)
}

type HLLVSetMatchTimer struct {
	GameMode    HLLVSetMatchTimerGameMode `json:"GameMode"`
	MatchLength int                       `json:"MatchLength"`
}

// SetMatchTimer Configure the match length in minutes for a specific game-mode. Warfare and Conquest can be set between 30 - 180 minutes. Offensive can be set between 10 - 60 minutes per capture point. Skirmish can be set between 10 - 60 minutes
func (c *HLLVConnection) SetMatchTimer(ctx context.Context, GameMode HLLVSetMatchTimerGameMode, MatchLength int) error {
	_, err := execCommand[HLLVSetMatchTimer, any](ctx, c.socket, HLLVSetMatchTimer{GameMode: GameMode, MatchLength: MatchLength})
	return err
}
