// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	HLLSetWarmupTimerGameModeConquest = "Conquest"
	HLLSetWarmupTimerGameModeSkirmish = "Skirmish"
	HLLSetWarmupTimerGameModeWarfare  = "Warfare"
)

type HLLSetWarmupTimerGameMode string

func (r HLLSetWarmupTimerGameMode) String() string {
	return string(r)
}

type HLLSetWarmupTimer struct {
	GameMode     HLLSetWarmupTimerGameMode `json:"GameMode"`
	WarmupLength int                       `json:"WarmupLength"`
}

// SetWarmupTimer Override the length of the warmup timer for a specific game-mode between 1 to 10 minutes.
func (c *HLLConnection) SetWarmupTimer(ctx context.Context, GameMode HLLSetWarmupTimerGameMode, WarmupLength int) error {
	_, err := execCommand[HLLSetWarmupTimer, any](ctx, c.socket, HLLSetWarmupTimer{GameMode: GameMode, WarmupLength: WarmupLength})
	return err
}
