// Code generated by go-hll-rcon; DO NOT EDIT

//go:build hllv
// +build hllv

package rconv2

import (
	"context"
)

const (
	SetMatchTimerGameModeConquest   = "Conquest"
	SetMatchTimerGameModeDomination = "Domination"
	SetMatchTimerGameModeOffensive  = "Offensive"
	SetMatchTimerGameModeWarfare    = "Warfare"
)

type SetMatchTimerGameMode string

func (r SetMatchTimerGameMode) String() string {
	return string(r)
}

type SetMatchTimer struct {
	GameMode    SetMatchTimerGameMode `json:"GameMode"`
	MatchLength int                   `json:"MatchLength"`
}

// SetMatchTimer Configure the match length in minutes for a specific game-mode. Warfare and Conquest can be set between 30 - 180 minutes. Offensive can be set between 10 - 60 minutes per capture point. Skirmish can be set between 10 - 60 minutes
func (c *Connection) SetMatchTimer(ctx context.Context, GameMode SetMatchTimerGameMode, MatchLength int) error {
	_, err := execCommand[SetMatchTimer, any](ctx, c.socket, SetMatchTimer{GameMode: GameMode, MatchLength: MatchLength})
	return err
}
