// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	HLLVSetWarmupTimerGameModeConquest   = "Conquest"
	HLLVSetWarmupTimerGameModeDomination = "Domination"
	HLLVSetWarmupTimerGameModeWarfare    = "Warfare"
)

type HLLVSetWarmupTimerGameMode string

func (r HLLVSetWarmupTimerGameMode) String() string {
	return string(r)
}

type HLLVSetWarmupTimer struct {
	GameMode     HLLVSetWarmupTimerGameMode `json:"GameMode"`
	WarmupLength int                        `json:"WarmupLength"`
}

// SetWarmupTimer Override the length of the warmup timer for a specific game-mode between 1 to 10 minutes.
func (c *HLLVConnection) SetWarmupTimer(ctx context.Context, GameMode HLLVSetWarmupTimerGameMode, WarmupLength int) error {
	_, err := execCommand[HLLVSetWarmupTimer, any](ctx, c.socket, HLLVSetWarmupTimer{GameMode: GameMode, WarmupLength: WarmupLength})
	return err
}
