// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	HLLSetDynamicWeatherEnabledEnableOff = false
	HLLSetDynamicWeatherEnabledEnableOn  = true
)

type HLLSetDynamicWeatherEnabledEnable any
type HLLSetDynamicWeatherEnabled struct {
	MapId  HLLMapName                        `json:"MapId"`
	Enable HLLSetDynamicWeatherEnabledEnable `json:"Enable"`
}

// SetDynamicWeatherEnabled Enable or disable dynamic weather for a specific map.
func (c *HLLConnection) SetDynamicWeatherEnabled(ctx context.Context, MapId HLLMapName, Enable HLLSetDynamicWeatherEnabledEnable) error {
	_, err := execCommand[HLLSetDynamicWeatherEnabled, any](ctx, c.socket, HLLSetDynamicWeatherEnabled{MapId: MapId, Enable: Enable})
	return err
}
