// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type SetWelcomeMessage struct {
	Message string `json:"Message"`
}

// SetWelcomeMessage Set Welcome Message: Send a message to the server.
func (c *Connection) SetWelcomeMessage(ctx context.Context, Message string) (any, error) {
	return execCommand[SetWelcomeMessage, any](ctx, c.socket, SetWelcomeMessage{Message: Message})

}
