// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type SetTeamSwitchCooldown struct {
	TeamSwitchTimer int32 `json:"TeamSwitchTimer"`
}

// SetTeamSwitchCooldown Set cooldown time for team switching.
func (c *Connection) SetTeamSwitchCooldown(ctx context.Context, TeamSwitchTimer int32) (any, error) {
	return execCommand[SetTeamSwitchCooldown, any](ctx, c.socket, SetTeamSwitchCooldown{TeamSwitchTimer: TeamSwitchTimer})

}
