// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	SetDynamicWeatherEnabledEnableOff                 = false
	SetDynamicWeatherEnabledEnableOn                  = true
	SetDynamicWeatherEnabledMapIdStmariedumontWarfare = "stmariedumont_warfare"
)

type SetDynamicWeatherEnabledMapId string
type SetDynamicWeatherEnabledEnable string
type SetDynamicWeatherEnabled struct {
	MapId  SetDynamicWeatherEnabledMapId  `json:"MapId"`
	Enable SetDynamicWeatherEnabledEnable `json:"Enable"`
}

// SetDynamicWeatherEnabled Enable or disable dynamic weather for a specific map.
func (c *Connection) SetDynamicWeatherEnabled(ctx context.Context, MapId SetDynamicWeatherEnabledMapId, Enable SetDynamicWeatherEnabledEnable) (any, error) {
	return execCommand[SetDynamicWeatherEnabled, any](ctx, c.socket, SetDynamicWeatherEnabled{MapId: MapId, Enable: Enable})

}
