// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type HLLSetWelcomeMessage struct {
	Message string `json:"Message"`
}

// SetWelcomeMessage Send a message to the server.
func (c *HLLConnection) SetWelcomeMessage(ctx context.Context, Message string) error {
	_, err := execCommand[HLLSetWelcomeMessage, any](ctx, c.socket, HLLSetWelcomeMessage{Message: Message})
	return err
}
