// Code generated by go-hll-rcon; DO NOT EDIT

//go:build hllv
// +build hllv

package rconv2

import (
	"context"
)

type SetNoticeMessage struct {
	Message string `json:"Message"`
}

// SetNoticeMessage Send a message to the server.
func (c *Connection) SetNoticeMessage(ctx context.Context, Message string) error {
	_, err := execCommand[SetNoticeMessage, any](ctx, c.socket, SetNoticeMessage{Message: Message})
	return err
}
