// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	HLLVSetDynamicWeatherEnabledEnableOff = false
	HLLVSetDynamicWeatherEnabledEnableOn  = true
)

type HLLVSetDynamicWeatherEnabledEnable any
type HLLVSetDynamicWeatherEnabled struct {
	MapId  HLLVMapName                        `json:"MapId"`
	Enable HLLVSetDynamicWeatherEnabledEnable `json:"Enable"`
}

// SetDynamicWeatherEnabled Enable or disable dynamic weather for a specific map.
func (c *HLLVConnection) SetDynamicWeatherEnabled(ctx context.Context, MapId HLLVMapName, Enable HLLVSetDynamicWeatherEnabledEnable) error {
	_, err := execCommand[HLLVSetDynamicWeatherEnabled, any](ctx, c.socket, HLLVSetDynamicWeatherEnabled{MapId: MapId, Enable: Enable})
	return err
}
