// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type SetAutoBalanceThreshold struct {
	AutoBalanceThreshold int32 `json:"AutoBalanceThreshold"`
}

// SetAutoBalanceThreshold Set the threshold value for teams when using auto balance.
func (c *Connection) SetAutoBalanceThreshold(ctx context.Context, AutoBalanceThreshold int32) (any, error) {
	return execCommand[SetAutoBalanceThreshold, any](ctx, c.socket, SetAutoBalanceThreshold{AutoBalanceThreshold: AutoBalanceThreshold})

}
