// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	HLLSetMatchTimerGameModeConquest  = "Conquest"
	HLLSetMatchTimerGameModeOffensive = "Offensive"
	HLLSetMatchTimerGameModeSkirmish  = "Skirmish"
	HLLSetMatchTimerGameModeWarfare   = "Warfare"
)

type HLLSetMatchTimerGameMode string

func (r HLLSetMatchTimerGameMode) String() string {
	return string(r)
}

type HLLSetMatchTimer struct {
	GameMode    HLLSetMatchTimerGameMode `json:"GameMode"`
	MatchLength int                      `json:"MatchLength"`
}

// SetMatchTimer Configure the match length in minutes for a specific game-mode. Warfare can be between 30 - 180 minutes. Offensive can be between 10 - 60 minutes per capture point. Skirmish can be between 10 - 60 minutes
func (c *HLLConnection) SetMatchTimer(ctx context.Context, GameMode HLLSetMatchTimerGameMode, MatchLength int) error {
	_, err := execCommand[HLLSetMatchTimer, any](ctx, c.socket, HLLSetMatchTimer{GameMode: GameMode, MatchLength: MatchLength})
	return err
}
