// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

const (
	SetVoteKickEnabledEnableOff = false
	SetVoteKickEnabledEnableOn  = true
)

type SetVoteKickEnabledEnable string
type SetVoteKickEnabled struct {
	Enable SetVoteKickEnabledEnable `json:"Enable"`
}

// SetVoteKickEnabled Set Vote to Kick Enabled: Enable or disable the vote to kick functionality.
func (c *Connection) SetVoteKickEnabled(ctx context.Context, Enable SetVoteKickEnabledEnable) (any, error) {
	return execCommand[SetVoteKickEnabled, any](ctx, c.socket, SetVoteKickEnabled{Enable: Enable})

}
