// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type SetIdleKickDuration struct {
	IdleTimeoutMinutes int32 `json:"IdleTimeoutMinutes"`
}

// SetIdleKickDuration Set how long a player can be idle before being kicked.
func (c *Connection) SetIdleKickDuration(ctx context.Context, IdleTimeoutMinutes int32) (any, error) {
	return execCommand[SetIdleKickDuration, any](ctx, c.socket, SetIdleKickDuration{IdleTimeoutMinutes: IdleTimeoutMinutes})

}
