// Code generated by go-hll-rcon; DO NOT EDIT
package rconv2

import (
	"context"
)

type ServerConnect struct {
}

// ServerConnect Server Connect
func (c *Connection) ServerConnect(ctx context.Context) (any, error) {
	return execCommand[ServerConnect, any](ctx, c.socket, ServerConnect{})

}
